language: cpp

compiler:
  - gcc
  - clang

sudo: true
dist: trusty

before_install:
  - sudo apt-get install build-essential imagemagick libsdl2-dev libimage-exiftool-perl

install: sudo ./tools/build-libpng.sh

script:
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [[ "$BUILDTYPE" == "GNUMAKE" ]]; then cd src && make && make test ;  fi
  - if [[ "$BUILDTYPE" == "ASAN" ]]; then mkdir build_cmake && cd build_cmake && cmake ../src -DMAKE_BUILD_TYPE=Release -DUSE_ASAN=ON && make && make test ; fi
  - if [[ "$BUILDTYPE" == "CMAKE" ]]; then mkdir build_cmake && cd build_cmake && cmake ../src -DMAKE_BUILD_TYPE=Release && make && make test ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d7137bab0c1e0a1d1089
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
